<?php

########################################################################
# Extension Manager/Repository config file for ext: "ddarchiv"
#
# Auto generated by Extension Builder 2012-03-25
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Village Archive',
	'description' => 'Online-Archiv für Vereine und Stadtteilarchive',
	'category' => 'plugin',
	'author' => 'Iris Schilke',
	'author_email' => 'ischilke@googlemail.com',
	'author_company' => 'Kaitzbach Webdesign',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
